SET NOCOUNT ON;

INSERT INTO Specialists (UserId, ExperienceYears, ExperienceLevel, HourlyRate, MinBookingNoticeHours, MaxSessionsPerDay, MaxSessionsPerWeek, CancellationNoticeHours, AllowCancellation, CancellationDeadlineHours, CancellationFeePercent, BookingPolicy, CancellationPolicy, IntroVideoUrl, CreatedAtUtc)
SELECT u.Id, S.ExpYrs, S.Level, S.Rate, 24, 8, 40, 24, 1, 24, 5.00,
    N'الحجز عبر المنصة. يجب تأكيد الموعد قبل 24 ساعة من الجلسة.',
    N'يمكن إلغاء الحجز مجاناً قبل 24 ساعة من الموعد. بعد ذلك يتم خصم 5% من قيمة الجلسة.',
    NULL,
    SYSDATETIMEOFFSET()
FROM (VALUES
    (N'ahmed.hassan@bosla.demo', 10, N'Senior', 350),
    (N'mona.ibrahim@bosla.demo', 6, N'Mid', 200),
    (N'nour.ahmed@bosla.demo', 5, N'Mid', 180),
    (N'sara.mohamed@bosla.demo', 9, N'Senior', 320),
    (N'ali.abdelrahman@bosla.demo', 6, N'Mid', 220),
    (N'hossam.ibrahim@bosla.demo', 4, N'Mid', 180),
    (N'mohamed.samir@bosla.demo', 5, N'Mid', 220),
    (N'dina.essam@bosla.demo', 6, N'Mid', 250),
    (N'yasmin.adel@bosla.demo', 7, N'Senior', 280),
    (N'mostafa.kamal@bosla.demo', 8, N'Senior', 350),
    (N'rania.abdelaziz@bosla.demo', 10, N'Senior', 400),
    (N'ayman.sherif@bosla.demo', 9, N'Senior', 380),
    (N'tarek.mahmoud@bosla.demo', 14, N'Lead', 550),
    (N'heba.ibrahim@bosla.demo', 11, N'Senior', 480),
    (N'waleed.hassan@bosla.demo', 9, N'Senior', 400),
    (N'nermeen.adel@bosla.demo', 8, N'Senior', 400),
    (N'ashraf.khalil@bosla.demo', 12, N'Lead', 500),
    (N'bassem.sameh@bosla.demo', 7, N'Senior', 350),
    (N'abdelrahman.nasser@bosla.demo', 7, N'Senior', 380),
    (N'fatma.elzahraa@bosla.demo', 5, N'Mid', 300),
    (N'mahmoud.sabry@bosla.demo', 8, N'Senior', 350),
    (N'galal.ahmed@bosla.demo', 9, N'Senior', 400),
    (N'samah.ibrahim@bosla.demo', 7, N'Senior', 350),
    (N'khaled.elrashidy@bosla.demo', 11, N'Senior', 450),
    (N'omar.nabil@bosla.demo', 12, N'Lead', 500),
    (N'hana.youssef@bosla.demo', 5, N'Mid', 250),
    (N'khaled.ali@bosla.demo', 14, N'Lead', 550),
    (N'mariam.karim@bosla.demo', 6, N'Mid', 300),
    (N'karim.hassan@bosla.demo', 7, N'Senior', 280),
    (N'nada.tarek@bosla.demo', 6, N'Mid', 240),
    (N'laila.mostafa@bosla.demo', 8, N'Senior', 350),
    (N'amr.elsayed@bosla.demo', 9, N'Senior', 400),
    (N'tamer.naguib@bosla.demo', 12, N'Lead', 500),
    (N'sherif.tawfik@bosla.demo', 5, N'Mid', 300),
    (N'reem.galal@bosla.demo', 7, N'Senior', 320),
    (N'hala.mahmoud@bosla.demo', 8, N'Senior', 400),
    (N'nihal.rashad@bosla.demo', 6, N'Mid', 280),
    (N'rasha.ezzat@bosla.demo', 9, N'Senior', 320),
    (N'ziad.amro@bosla.demo', 10, N'Senior', 450),
    (N'mai.abdelhamid@bosla.demo', 6, N'Mid', 280),
    (N'islam.ahmed@bosla.demo', 10, N'Senior', 450),
    (N'marwa.said@bosla.demo', 13, N'Lead', 520),
    (N'nesrine.khaled@bosla.demo', 5, N'Mid', 250),
    (N'hassan.younis@bosla.demo', 8, N'Senior', 350),
    (N'aya.yasser@bosla.demo', 5, N'Mid', 300),
    (N'hisham.lotfy@bosla.demo', 9, N'Senior', 400),
    (N'nadine.emad@bosla.demo', 4, N'Mid', 280),
    (N'hany.magdy@bosla.demo', 15, N'Lead', 600),
    (N'salma.hassan@bosla.demo', 6, N'Mid', 250),
    (N'youssef.mahmoud@bosla.demo', 8, N'Senior', 300)
) AS S(Email, ExpYrs, Level, Rate)
INNER JOIN AspNetUsers u ON u.Email = S.Email
WHERE NOT EXISTS (SELECT 1 FROM Specialists sp WHERE sp.UserId = u.Id);

PRINT N'Inserted 50 specialists.';
GO

INSERT INTO SpecialistVerifications (SpecialistId, Status, IsSubmitted, SubmittedAt, ReviewedAt, LastUpdatedAt, CreatedAtUtc)
SELECT sp.Id, N'Approved', 1,
    DATEADD(DAY, -30, SYSDATETIME()),
    DATEADD(DAY, -28, SYSDATETIME()),
    DATEADD(DAY, -28, SYSDATETIME()),
    SYSDATETIMEOFFSET()
FROM Specialists sp
INNER JOIN AspNetUsers u ON u.Id = sp.UserId
WHERE u.Email IN (
    N'ahmed.hassan@bosla.demo',
    N'mona.ibrahim@bosla.demo',
    N'nour.ahmed@bosla.demo',
    N'sara.mohamed@bosla.demo',
    N'ali.abdelrahman@bosla.demo',
    N'hossam.ibrahim@bosla.demo',
    N'mohamed.samir@bosla.demo',
    N'dina.essam@bosla.demo',
    N'yasmin.adel@bosla.demo',
    N'mostafa.kamal@bosla.demo',
    N'rania.abdelaziz@bosla.demo',
    N'ayman.sherif@bosla.demo',
    N'tarek.mahmoud@bosla.demo',
    N'heba.ibrahim@bosla.demo',
    N'waleed.hassan@bosla.demo',
    N'nermeen.adel@bosla.demo',
    N'ashraf.khalil@bosla.demo',
    N'bassem.sameh@bosla.demo',
    N'abdelrahman.nasser@bosla.demo',
    N'fatma.elzahraa@bosla.demo',
    N'mahmoud.sabry@bosla.demo',
    N'galal.ahmed@bosla.demo',
    N'samah.ibrahim@bosla.demo',
    N'khaled.elrashidy@bosla.demo',
    N'omar.nabil@bosla.demo',
    N'hana.youssef@bosla.demo',
    N'khaled.ali@bosla.demo',
    N'mariam.karim@bosla.demo',
    N'karim.hassan@bosla.demo',
    N'nada.tarek@bosla.demo',
    N'laila.mostafa@bosla.demo',
    N'amr.elsayed@bosla.demo',
    N'tamer.naguib@bosla.demo',
    N'sherif.tawfik@bosla.demo',
    N'reem.galal@bosla.demo',
    N'hala.mahmoud@bosla.demo',
    N'nihal.rashad@bosla.demo',
    N'rasha.ezzat@bosla.demo',
    N'ziad.amro@bosla.demo',
    N'mai.abdelhamid@bosla.demo',
    N'islam.ahmed@bosla.demo',
    N'marwa.said@bosla.demo',
    N'nesrine.khaled@bosla.demo',
    N'hassan.younis@bosla.demo',
    N'aya.yasser@bosla.demo',
    N'hisham.lotfy@bosla.demo',
    N'nadine.emad@bosla.demo',
    N'hany.magdy@bosla.demo',
    N'salma.hassan@bosla.demo',
    N'youssef.mahmoud@bosla.demo'
)
AND NOT EXISTS (SELECT 1 FROM SpecialistVerifications sv WHERE sv.SpecialistId = sp.Id);

PRINT N'Inserted 50 specialist verifications.';
GO
