SET NOCOUNT ON;

WITH SpecialistExpertiseData AS (
    SELECT u.Email, D.ExpertiseName
    FROM (VALUES
        (N'ahmed.hassan@bosla.demo', N'تطوير Backend'),
        (N'ahmed.hassan@bosla.demo', N'الحوسبة السحابية'),
        (N'ahmed.hassan@bosla.demo', N'DevOps'),
        (N'mona.ibrahim@bosla.demo', N'تطوير Backend'),
        (N'mona.ibrahim@bosla.demo', N'الحوسبة السحابية'),
        (N'mona.ibrahim@bosla.demo', N'علم البيانات'),
        (N'nour.ahmed@bosla.demo', N'تطوير Backend'),
        (N'nour.ahmed@bosla.demo', N'DevOps'),
        (N'nour.ahmed@bosla.demo', N'الأمن السيبراني'),
        (N'sara.mohamed@bosla.demo', N'تطوير Frontend'),
        (N'sara.mohamed@bosla.demo', N'تطوير تطبيقات الجوال'),
        (N'sara.mohamed@bosla.demo', N'الحوسبة السحابية'),
        (N'ali.abdelrahman@bosla.demo', N'تطوير Frontend'),
        (N'ali.abdelrahman@bosla.demo', N'تطوير Backend'),
        (N'ali.abdelrahman@bosla.demo', N'DevOps'),
        (N'hossam.ibrahim@bosla.demo', N'تطوير Frontend'),
        (N'hossam.ibrahim@bosla.demo', N'تطوير تطبيقات الجوال'),
        (N'hossam.ibrahim@bosla.demo', N'الحوسبة السحابية'),
        (N'mohamed.samir@bosla.demo', N'تطوير تطبيقات الجوال'),
        (N'mohamed.samir@bosla.demo', N'تطوير Frontend'),
        (N'mohamed.samir@bosla.demo', N'الحوسبة السحابية'),
        (N'dina.essam@bosla.demo', N'تطوير تطبيقات الجوال'),
        (N'dina.essam@bosla.demo', N'تطوير Frontend'),
        (N'dina.essam@bosla.demo', N'تطوير Backend'),
        (N'yasmin.adel@bosla.demo', N'تطوير تطبيقات الجوال'),
        (N'yasmin.adel@bosla.demo', N'الحوسبة السحابية'),
        (N'yasmin.adel@bosla.demo', N'تعلم الآلة'),
        (N'mostafa.kamal@bosla.demo', N'DevOps'),
        (N'mostafa.kamal@bosla.demo', N'الحوسبة السحابية'),
        (N'mostafa.kamal@bosla.demo', N'الأمن السيبراني'),
        (N'rania.abdelaziz@bosla.demo', N'DevOps'),
        (N'rania.abdelaziz@bosla.demo', N'الحوسبة السحابية'),
        (N'rania.abdelaziz@bosla.demo', N'تطوير Backend'),
        (N'ayman.sherif@bosla.demo', N'DevOps'),
        (N'ayman.sherif@bosla.demo', N'الحوسبة السحابية'),
        (N'ayman.sherif@bosla.demo', N'علم البيانات'),
        (N'tarek.mahmoud@bosla.demo', N'الحوسبة السحابية'),
        (N'tarek.mahmoud@bosla.demo', N'DevOps'),
        (N'tarek.mahmoud@bosla.demo', N'الأمن السيبراني'),
        (N'heba.ibrahim@bosla.demo', N'الحوسبة السحابية'),
        (N'heba.ibrahim@bosla.demo', N'DevOps'),
        (N'heba.ibrahim@bosla.demo', N'علم البيانات'),
        (N'waleed.hassan@bosla.demo', N'الحوسبة السحابية'),
        (N'waleed.hassan@bosla.demo', N'تعلم الآلة'),
        (N'waleed.hassan@bosla.demo', N'علم البيانات'),
        (N'nermeen.adel@bosla.demo', N'علم البيانات'),
        (N'nermeen.adel@bosla.demo', N'تعلم الآلة'),
        (N'nermeen.adel@bosla.demo', N'الحوسبة السحابية'),
        (N'ashraf.khalil@bosla.demo', N'علم البيانات'),
        (N'ashraf.khalil@bosla.demo', N'تعلم الآلة'),
        (N'ashraf.khalil@bosla.demo', N'تطوير Backend'),
        (N'bassem.sameh@bosla.demo', N'علم البيانات'),
        (N'bassem.sameh@bosla.demo', N'الحوسبة السحابية'),
        (N'bassem.sameh@bosla.demo', N'DevOps'),
        (N'abdelrahman.nasser@bosla.demo', N'تعلم الآلة'),
        (N'abdelrahman.nasser@bosla.demo', N'علم البيانات'),
        (N'abdelrahman.nasser@bosla.demo', N'الحوسبة السحابية'),
        (N'fatma.elzahraa@bosla.demo', N'تعلم الآلة'),
        (N'fatma.elzahraa@bosla.demo', N'علم البيانات'),
        (N'fatma.elzahraa@bosla.demo', N'تطوير Backend'),
        (N'mahmoud.sabry@bosla.demo', N'تعلم الآلة'),
        (N'mahmoud.sabry@bosla.demo', N'علم البيانات'),
        (N'mahmoud.sabry@bosla.demo', N'الحوسبة السحابية'),
        (N'galal.ahmed@bosla.demo', N'الأمن السيبراني'),
        (N'galal.ahmed@bosla.demo', N'الحوسبة السحابية'),
        (N'galal.ahmed@bosla.demo', N'DevOps'),
        (N'samah.ibrahim@bosla.demo', N'الأمن السيبراني'),
        (N'samah.ibrahim@bosla.demo', N'تطوير Backend'),
        (N'samah.ibrahim@bosla.demo', N'الحوسبة السحابية'),
        (N'khaled.elrashidy@bosla.demo', N'الأمن السيبراني'),
        (N'khaled.elrashidy@bosla.demo', N'الحوسبة السحابية'),
        (N'khaled.elrashidy@bosla.demo', N'علم البيانات'),
        (N'omar.nabil@bosla.demo', N'طب عام'),
        (N'omar.nabil@bosla.demo', N'تغذية ولياقة'),
        (N'omar.nabil@bosla.demo', N'صيدلة'),
        (N'hana.youssef@bosla.demo', N'طب عام'),
        (N'hana.youssef@bosla.demo', N'تغذية ولياقة'),
        (N'hana.youssef@bosla.demo', N'إدارة أعمال'),
        (N'khaled.ali@bosla.demo', N'طب أسنان'),
        (N'khaled.ali@bosla.demo', N'طب عام'),
        (N'khaled.ali@bosla.demo', N'صيدلة'),
        (N'mariam.karim@bosla.demo', N'طب أسنان'),
        (N'mariam.karim@bosla.demo', N'طب عام'),
        (N'mariam.karim@bosla.demo', N'إدارة أعمال'),
        (N'karim.hassan@bosla.demo', N'صيدلة'),
        (N'karim.hassan@bosla.demo', N'طب عام'),
        (N'karim.hassan@bosla.demo', N'إدارة أعمال'),
        (N'nada.tarek@bosla.demo', N'صيدلة'),
        (N'nada.tarek@bosla.demo', N'طب عام'),
        (N'nada.tarek@bosla.demo', N'تسويق'),
        (N'laila.mostafa@bosla.demo', N'هندسة مدنية'),
        (N'laila.mostafa@bosla.demo', N'إدارة أعمال'),
        (N'laila.mostafa@bosla.demo', N'قانون'),
        (N'amr.elsayed@bosla.demo', N'هندسة مدنية'),
        (N'amr.elsayed@bosla.demo', N'إدارة أعمال'),
        (N'amr.elsayed@bosla.demo', N'الحوسبة السحابية'),
        (N'tamer.naguib@bosla.demo', N'هندسة ميكانيكا'),
        (N'tamer.naguib@bosla.demo', N'إدارة أعمال'),
        (N'tamer.naguib@bosla.demo', N'الحوسبة السحابية'),
        (N'sherif.tawfik@bosla.demo', N'هندسة ميكانيكا'),
        (N'sherif.tawfik@bosla.demo', N'إدارة أعمال'),
        (N'sherif.tawfik@bosla.demo', N'DevOps'),
        (N'reem.galal@bosla.demo', N'هندسة كهرباء'),
        (N'reem.galal@bosla.demo', N'الحوسبة السحابية'),
        (N'reem.galal@bosla.demo', N'إدارة أعمال'),
        (N'hala.mahmoud@bosla.demo', N'هندسة كهرباء'),
        (N'hala.mahmoud@bosla.demo', N'علم البيانات'),
        (N'hala.mahmoud@bosla.demo', N'إدارة أعمال'),
        (N'nihal.rashad@bosla.demo', N'قانون'),
        (N'nihal.rashad@bosla.demo', N'إدارة أعمال'),
        (N'nihal.rashad@bosla.demo', N'محاسبة'),
        (N'rasha.ezzat@bosla.demo', N'قانون'),
        (N'rasha.ezzat@bosla.demo', N'محاسبة'),
        (N'rasha.ezzat@bosla.demo', N'إدارة أعمال'),
        (N'ziad.amro@bosla.demo', N'قانون'),
        (N'ziad.amro@bosla.demo', N'إدارة أعمال'),
        (N'ziad.amro@bosla.demo', N'تسويق'),
        (N'mai.abdelhamid@bosla.demo', N'محاسبة'),
        (N'mai.abdelhamid@bosla.demo', N'إدارة أعمال'),
        (N'mai.abdelhamid@bosla.demo', N'قانون'),
        (N'islam.ahmed@bosla.demo', N'محاسبة'),
        (N'islam.ahmed@bosla.demo', N'إدارة أعمال'),
        (N'islam.ahmed@bosla.demo', N'الحوسبة السحابية'),
        (N'marwa.said@bosla.demo', N'تسويق'),
        (N'marwa.said@bosla.demo', N'إدارة أعمال'),
        (N'marwa.said@bosla.demo', N'فنون'),
        (N'nesrine.khaled@bosla.demo', N'تسويق'),
        (N'nesrine.khaled@bosla.demo', N'إدارة أعمال'),
        (N'nesrine.khaled@bosla.demo', N'علم البيانات'),
        (N'hassan.younis@bosla.demo', N'تدريس'),
        (N'hassan.younis@bosla.demo', N'فنون'),
        (N'hassan.younis@bosla.demo', N'إدارة أعمال'),
        (N'aya.yasser@bosla.demo', N'تدريس'),
        (N'aya.yasser@bosla.demo', N'علم البيانات'),
        (N'aya.yasser@bosla.demo', N'تعلم الآلة'),
        (N'hisham.lotfy@bosla.demo', N'فنون'),
        (N'hisham.lotfy@bosla.demo', N'تسويق'),
        (N'hisham.lotfy@bosla.demo', N'تدريس'),
        (N'nadine.emad@bosla.demo', N'فنون'),
        (N'nadine.emad@bosla.demo', N'تسويق'),
        (N'nadine.emad@bosla.demo', N'تطوير Frontend'),
        (N'hany.magdy@bosla.demo', N'إدارة أعمال'),
        (N'hany.magdy@bosla.demo', N'قانون'),
        (N'hany.magdy@bosla.demo', N'محاسبة'),
        (N'salma.hassan@bosla.demo', N'إدارة أعمال'),
        (N'salma.hassan@bosla.demo', N'تسويق'),
        (N'salma.hassan@bosla.demo', N'تغذية ولياقة'),
        (N'youssef.mahmoud@bosla.demo', N'تغذية ولياقة'),
        (N'youssef.mahmoud@bosla.demo', N'طب عام'),
        (N'youssef.mahmoud@bosla.demo', N'إدارة أعمال')
    ) AS D(Email, ExpertiseName)
    INNER JOIN AspNetUsers u ON u.Email = D.Email
)
INSERT INTO SpecialistExpertise (SpecialistId, ExpertiseId)
SELECT sp.Id, ex.Id
FROM SpecialistExpertiseData
INNER JOIN Specialists sp ON sp.UserId = (SELECT Id FROM AspNetUsers WHERE Email = SpecialistExpertiseData.Email)
INNER JOIN Expertises ex ON ex.Name = SpecialistExpertiseData.ExpertiseName
WHERE NOT EXISTS (
    SELECT 1 FROM SpecialistExpertise se
    WHERE se.SpecialistId = sp.Id AND se.ExpertiseId = ex.Id
);

PRINT N'Inserted specialist-expertise assignments.';
GO
