SET NOCOUNT ON;

PRINT N'Seeding Industries...';
INSERT INTO Industries (Name)
SELECT v.Name FROM (VALUES
    (N'الرعاية الصحية'),
    (N'التعليم'),
    (N'التكنولوجيا'),
    (N'المالية والمصرفية'),
    (N'المقاولات والبناء'),
    (N'التسويق والإعلان'),
    (N'القانون والاستشارات'),
    (N'الفنون والإبداع'),
    (N'الرياضة واللياقة'),
    (N'السياحة والضيافة')
) AS v(Name)
WHERE NOT EXISTS (SELECT 1 FROM Industries WHERE Name = v.Name);
PRINT N'Seeded Industries.';

PRINT N'Seeding Skills...';
INSERT INTO Skills (Name)
SELECT v.Name FROM (VALUES
    (N'قيادة الفريق'),
    (N'إدارة المشاريع'),
    (N'التواصل الفعال'),
    (N'التفكير التحليلي'),
    (N'حل المشكلات'),
    (N'العمل تحت الضغط'),
    (N'الإبداع'),
    (N'التفاوض'),
    (N'التخطيط الاستراتيجي'),
    (N'التحليل المالي'),
    (N'البرمجة'),
    (N'التصميم'),
    (N'الكتابة'),
    (N'التدريب'),
    (N'البيع'),
    (N'التسويق الرقمي'),
    (N'إدارة الوقت'),
    (N'البحث العلمي'),
    (N'التحليل الإحصائي'),
    (N'التحدث أمام الجمهور')
) AS v(Name)
WHERE NOT EXISTS (SELECT 1 FROM Skills WHERE Name = v.Name);
PRINT N'Seeded Skills.';

PRINT N'Seeding Tools...';
INSERT INTO Tools (Name)
SELECT v.Name FROM (VALUES
    (N'Microsoft Teams'),
    (N'Zoom'),
    (N'Slack'),
    (N'Jira'),
    (N'Trello'),
    (N'Google Analytics'),
    (N'Salesforce'),
    (N'Tableau'),
    (N'Power BI'),
    (N'Figma'),
    (N'Adobe Photoshop'),
    (N'GitHub'),
    (N'Docker'),
    (N'Kubernetes'),
    (N'AWS')
) AS v(Name)
WHERE NOT EXISTS (SELECT 1 FROM Tools WHERE Name = v.Name);
PRINT N'Seeded Tools.';

PRINT N'Seeding SpecialistIndustries...';
INSERT INTO SpecialistIndustries (SpecialistId, IndustryId)
SELECT sp.Id, ind.Id
FROM (VALUES
    -- Tech: التكنولوجيا + secondary industry
    (N'ahmed.hassan@bosla.demo',     N'التكنولوجيا'),
    (N'ahmed.hassan@bosla.demo',     N'الرعاية الصحية'),
    (N'mona.ibrahim@bosla.demo',     N'التكنولوجيا'),
    (N'mona.ibrahim@bosla.demo',     N'التعليم'),
    (N'nour.ahmed@bosla.demo',       N'التكنولوجيا'),
    (N'nour.ahmed@bosla.demo',       N'المالية والمصرفية'),
    (N'sara.mohamed@bosla.demo',     N'التكنولوجيا'),
    (N'sara.mohamed@bosla.demo',     N'التعليم'),
    (N'ali.abdelrahman@bosla.demo',  N'التكنولوجيا'),
    (N'ali.abdelrahman@bosla.demo',  N'المالية والمصرفية'),
    (N'hossam.ibrahim@bosla.demo',   N'التكنولوجيا'),
    (N'hossam.ibrahim@bosla.demo',   N'التسويق والإعلان'),
    (N'mohamed.samir@bosla.demo',    N'التكنولوجيا'),
    (N'mohamed.samir@bosla.demo',    N'التعليم'),
    (N'dina.essam@bosla.demo',       N'التكنولوجيا'),
    (N'dina.essam@bosla.demo',       N'الفنون والإبداع'),
    (N'yasmin.adel@bosla.demo',      N'التكنولوجيا'),
    (N'yasmin.adel@bosla.demo',      N'السياحة والضيافة'),
    (N'mostafa.kamal@bosla.demo',    N'التكنولوجيا'),
    (N'mostafa.kamal@bosla.demo',    N'المالية والمصرفية'),
    (N'rania.abdelaziz@bosla.demo',  N'التكنولوجيا'),
    (N'rania.abdelaziz@bosla.demo',  N'الرعاية الصحية'),
    (N'ayman.sherif@bosla.demo',     N'التكنولوجيا'),
    (N'ayman.sherif@bosla.demo',     N'المقاولات والبناء'),
    (N'tarek.mahmoud@bosla.demo',    N'التكنولوجيا'),
    (N'tarek.mahmoud@bosla.demo',    N'المالية والمصرفية'),
    (N'heba.ibrahim@bosla.demo',     N'التكنولوجيا'),
    (N'heba.ibrahim@bosla.demo',     N'الرعاية الصحية'),
    (N'waleed.hassan@bosla.demo',    N'التكنولوجيا'),
    (N'waleed.hassan@bosla.demo',    N'التعليم'),
    (N'nermeen.adel@bosla.demo',     N'التكنولوجيا'),
    (N'nermeen.adel@bosla.demo',     N'الرعاية الصحية'),
    (N'ashraf.khalil@bosla.demo',    N'التكنولوجيا'),
    (N'ashraf.khalil@bosla.demo',    N'المالية والمصرفية'),
    (N'bassem.sameh@bosla.demo',     N'التكنولوجيا'),
    (N'bassem.sameh@bosla.demo',     N'التسويق والإعلان'),
    (N'abdelrahman.nasser@bosla.demo', N'التكنولوجيا'),
    (N'abdelrahman.nasser@bosla.demo', N'الرعاية الصحية'),
    (N'fatma.elzahraa@bosla.demo',   N'التكنولوجيا'),
    (N'fatma.elzahraa@bosla.demo',   N'الفنون والإبداع'),
    (N'mahmoud.sabry@bosla.demo',    N'التكنولوجيا'),
    (N'mahmoud.sabry@bosla.demo',    N'التعليم'),
    (N'galal.ahmed@bosla.demo',      N'التكنولوجيا'),
    (N'galal.ahmed@bosla.demo',      N'المالية والمصرفية'),
    (N'samah.ibrahim@bosla.demo',    N'التكنولوجيا'),
    (N'samah.ibrahim@bosla.demo',    N'القانون والاستشارات'),
    (N'khaled.elrashidy@bosla.demo', N'التكنولوجيا'),
    (N'khaled.elrashidy@bosla.demo', N'القانون والاستشارات'),
    -- Non-Tech
    (N'omar.nabil@bosla.demo',       N'الرعاية الصحية'),
    (N'omar.nabil@bosla.demo',       N'الرياضة واللياقة'),
    (N'hana.youssef@bosla.demo',     N'الرعاية الصحية'),
    (N'hana.youssef@bosla.demo',     N'التعليم'),
    (N'khaled.ali@bosla.demo',       N'الرعاية الصحية'),
    (N'khaled.ali@bosla.demo',       N'التعليم'),
    (N'mariam.karim@bosla.demo',     N'الرعاية الصحية'),
    (N'mariam.karim@bosla.demo',     N'الفنون والإبداع'),
    (N'karim.hassan@bosla.demo',     N'الرعاية الصحية'),
    (N'karim.hassan@bosla.demo',     N'التعليم'),
    (N'nada.tarek@bosla.demo',       N'الرعاية الصحية'),
    (N'nada.tarek@bosla.demo',       N'التسويق والإعلان'),
    (N'laila.mostafa@bosla.demo',    N'المقاولات والبناء'),
    (N'laila.mostafa@bosla.demo',    N'التكنولوجيا'),
    (N'amr.elsayed@bosla.demo',      N'المقاولات والبناء'),
    (N'amr.elsayed@bosla.demo',      N'السياحة والضيافة'),
    (N'tamer.naguib@bosla.demo',     N'المقاولات والبناء'),
    (N'tamer.naguib@bosla.demo',     N'التكنولوجيا'),
    (N'sherif.tawfik@bosla.demo',    N'المقاولات والبناء'),
    (N'sherif.tawfik@bosla.demo',    N'التعليم'),
    (N'reem.galal@bosla.demo',       N'المقاولات والبناء'),
    (N'reem.galal@bosla.demo',       N'المالية والمصرفية'),
    (N'hala.mahmoud@bosla.demo',     N'المقاولات والبناء'),
    (N'hala.mahmoud@bosla.demo',     N'التكنولوجيا'),
    (N'nihal.rashad@bosla.demo',     N'القانون والاستشارات'),
    (N'nihal.rashad@bosla.demo',     N'التعليم'),
    (N'rasha.ezzat@bosla.demo',      N'القانون والاستشارات'),
    (N'rasha.ezzat@bosla.demo',      N'المالية والمصرفية'),
    (N'ziad.amro@bosla.demo',        N'القانون والاستشارات'),
    (N'ziad.amro@bosla.demo',        N'التسويق والإعلان'),
    (N'mai.abdelhamid@bosla.demo',   N'المالية والمصرفية'),
    (N'mai.abdelhamid@bosla.demo',   N'القانون والاستشارات'),
    (N'islam.ahmed@bosla.demo',      N'المالية والمصرفية'),
    (N'islam.ahmed@bosla.demo',      N'التكنولوجيا'),
    (N'marwa.said@bosla.demo',       N'التسويق والإعلان'),
    (N'marwa.said@bosla.demo',       N'التكنولوجيا'),
    (N'nesrine.khaled@bosla.demo',   N'التسويق والإعلان'),
    (N'nesrine.khaled@bosla.demo',   N'الفنون والإبداع'),
    (N'hassan.younis@bosla.demo',    N'التعليم'),
    (N'hassan.younis@bosla.demo',    N'الفنون والإبداع'),
    (N'aya.yasser@bosla.demo',       N'التعليم'),
    (N'aya.yasser@bosla.demo',       N'التكنولوجيا'),
    (N'hisham.lotfy@bosla.demo',     N'الفنون والإبداع'),
    (N'hisham.lotfy@bosla.demo',     N'التعليم'),
    (N'nadine.emad@bosla.demo',      N'الفنون والإبداع'),
    (N'nadine.emad@bosla.demo',      N'التسويق والإعلان'),
    (N'hany.magdy@bosla.demo',       N'المالية والمصرفية'),
    (N'hany.magdy@bosla.demo',       N'التعليم'),
    (N'salma.hassan@bosla.demo',     N'المالية والمصرفية'),
    (N'salma.hassan@bosla.demo',     N'التعليم'),
    (N'youssef.mahmoud@bosla.demo',  N'الرياضة واللياقة'),
    (N'youssef.mahmoud@bosla.demo',  N'الرعاية الصحية')
) AS D(Email, IndustryName)
INNER JOIN Specialists sp ON sp.UserId = (SELECT Id FROM AspNetUsers WHERE Email = D.Email)
INNER JOIN Industries ind ON ind.Name = D.IndustryName
WHERE NOT EXISTS (
    SELECT 1 FROM SpecialistIndustries si
    WHERE si.SpecialistId = sp.Id AND si.IndustryId = ind.Id
);
PRINT N'Seeded SpecialistIndustries (100 records).';

PRINT N'Seeding SpecialistSkills...';
INSERT INTO SpecialistSkills (SpecialistId, SkillId)
SELECT sp.Id, sk.Id
FROM (VALUES
    -- Tech specialists
    (N'ahmed.hassan@bosla.demo',     N'قيادة الفريق'),
    (N'ahmed.hassan@bosla.demo',     N'إدارة المشاريع'),
    (N'ahmed.hassan@bosla.demo',     N'البرمجة'),
    (N'mona.ibrahim@bosla.demo',     N'البرمجة'),
    (N'mona.ibrahim@bosla.demo',     N'حل المشكلات'),
    (N'mona.ibrahim@bosla.demo',     N'العمل تحت الضغط'),
    (N'nour.ahmed@bosla.demo',       N'البرمجة'),
    (N'nour.ahmed@bosla.demo',       N'التفكير التحليلي'),
    (N'nour.ahmed@bosla.demo',       N'التواصل الفعال'),
    (N'sara.mohamed@bosla.demo',     N'التصميم'),
    (N'sara.mohamed@bosla.demo',     N'البرمجة'),
    (N'sara.mohamed@bosla.demo',     N'التواصل الفعال'),
    (N'ali.abdelrahman@bosla.demo',  N'البرمجة'),
    (N'ali.abdelrahman@bosla.demo',  N'إدارة المشاريع'),
    (N'ali.abdelrahman@bosla.demo',  N'حل المشكلات'),
    (N'hossam.ibrahim@bosla.demo',   N'البرمجة'),
    (N'hossam.ibrahim@bosla.demo',   N'الإبداع'),
    (N'hossam.ibrahim@bosla.demo',   N'العمل تحت الضغط'),
    (N'mohamed.samir@bosla.demo',    N'البرمجة'),
    (N'mohamed.samir@bosla.demo',    N'التصميم'),
    (N'mohamed.samir@bosla.demo',    N'حل المشكلات'),
    (N'dina.essam@bosla.demo',       N'البرمجة'),
    (N'dina.essam@bosla.demo',       N'التصميم'),
    (N'dina.essam@bosla.demo',       N'التواصل الفعال'),
    (N'yasmin.adel@bosla.demo',      N'البرمجة'),
    (N'yasmin.adel@bosla.demo',      N'الإبداع'),
    (N'yasmin.adel@bosla.demo',      N'إدارة الوقت'),
    (N'mostafa.kamal@bosla.demo',    N'إدارة المشاريع'),
    (N'mostafa.kamal@bosla.demo',    N'العمل تحت الضغط'),
    (N'mostafa.kamal@bosla.demo',    N'حل المشكلات'),
    (N'rania.abdelaziz@bosla.demo',  N'قيادة الفريق'),
    (N'rania.abdelaziz@bosla.demo',  N'إدارة المشاريع'),
    (N'rania.abdelaziz@bosla.demo',  N'التخطيط الاستراتيجي'),
    (N'ayman.sherif@bosla.demo',     N'حل المشكلات'),
    (N'ayman.sherif@bosla.demo',     N'العمل تحت الضغط'),
    (N'ayman.sherif@bosla.demo',     N'إدارة الوقت'),
    (N'tarek.mahmoud@bosla.demo',    N'التخطيط الاستراتيجي'),
    (N'tarek.mahmoud@bosla.demo',    N'قيادة الفريق'),
    (N'tarek.mahmoud@bosla.demo',    N'إدارة المشاريع'),
    (N'heba.ibrahim@bosla.demo',     N'قيادة الفريق'),
    (N'heba.ibrahim@bosla.demo',     N'التخطيط الاستراتيجي'),
    (N'heba.ibrahim@bosla.demo',     N'حل المشكلات'),
    (N'waleed.hassan@bosla.demo',    N'البرمجة'),
    (N'waleed.hassan@bosla.demo',    N'التفكير التحليلي'),
    (N'waleed.hassan@bosla.demo',    N'إدارة المشاريع'),
    (N'nermeen.adel@bosla.demo',     N'التفكير التحليلي'),
    (N'nermeen.adel@bosla.demo',     N'البحث العلمي'),
    (N'nermeen.adel@bosla.demo',     N'التحليل الإحصائي'),
    (N'ashraf.khalil@bosla.demo',    N'التفكير التحليلي'),
    (N'ashraf.khalil@bosla.demo',    N'قيادة الفريق'),
    (N'ashraf.khalil@bosla.demo',    N'التحليل الإحصائي'),
    (N'bassem.sameh@bosla.demo',     N'التفكير التحليلي'),
    (N'bassem.sameh@bosla.demo',     N'حل المشكلات'),
    (N'bassem.sameh@bosla.demo',     N'البرمجة'),
    (N'abdelrahman.nasser@bosla.demo', N'البحث العلمي'),
    (N'abdelrahman.nasser@bosla.demo', N'التفكير التحليلي'),
    (N'abdelrahman.nasser@bosla.demo', N'البرمجة'),
    (N'fatma.elzahraa@bosla.demo',   N'البحث العلمي'),
    (N'fatma.elzahraa@bosla.demo',   N'الإبداع'),
    (N'fatma.elzahraa@bosla.demo',   N'حل المشكلات'),
    (N'mahmoud.sabry@bosla.demo',    N'البحث العلمي'),
    (N'mahmoud.sabry@bosla.demo',    N'التفكير التحليلي'),
    (N'mahmoud.sabry@bosla.demo',    N'التحليل الإحصائي'),
    (N'galal.ahmed@bosla.demo',      N'التفكير التحليلي'),
    (N'galal.ahmed@bosla.demo',      N'حل المشكلات'),
    (N'galal.ahmed@bosla.demo',      N'العمل تحت الضغط'),
    (N'samah.ibrahim@bosla.demo',    N'حل المشكلات'),
    (N'samah.ibrahim@bosla.demo',    N'البرمجة'),
    (N'samah.ibrahim@bosla.demo',    N'الإبداع'),
    (N'khaled.elrashidy@bosla.demo', N'التفكير التحليلي'),
    (N'khaled.elrashidy@bosla.demo', N'التواصل الفعال'),
    (N'khaled.elrashidy@bosla.demo', N'إدارة المشاريع'),
    -- Non-Tech
    (N'omar.nabil@bosla.demo',       N'التواصل الفعال'),
    (N'omar.nabil@bosla.demo',       N'قيادة الفريق'),
    (N'omar.nabil@bosla.demo',       N'العمل تحت الضغط'),
    (N'hana.youssef@bosla.demo',     N'التواصل الفعال'),
    (N'hana.youssef@bosla.demo',     N'إدارة الوقت'),
    (N'hana.youssef@bosla.demo',     N'العمل تحت الضغط'),
    (N'khaled.ali@bosla.demo',       N'التواصل الفعال'),
    (N'khaled.ali@bosla.demo',       N'قيادة الفريق'),
    (N'khaled.ali@bosla.demo',       N'إدارة الوقت'),
    (N'mariam.karim@bosla.demo',     N'التواصل الفعال'),
    (N'mariam.karim@bosla.demo',     N'الإبداع'),
    (N'mariam.karim@bosla.demo',     N'إدارة الوقت'),
    (N'karim.hassan@bosla.demo',     N'التواصل الفعال'),
    (N'karim.hassan@bosla.demo',     N'البحث العلمي'),
    (N'karim.hassan@bosla.demo',     N'إدارة الوقت'),
    (N'nada.tarek@bosla.demo',       N'التواصل الفعال'),
    (N'nada.tarek@bosla.demo',       N'التسويق الرقمي'),
    (N'nada.tarek@bosla.demo',       N'إدارة الوقت'),
    (N'laila.mostafa@bosla.demo',    N'إدارة المشاريع'),
    (N'laila.mostafa@bosla.demo',    N'قيادة الفريق'),
    (N'laila.mostafa@bosla.demo',    N'حل المشكلات'),
    (N'amr.elsayed@bosla.demo',      N'إدارة المشاريع'),
    (N'amr.elsayed@bosla.demo',      N'التخطيط الاستراتيجي'),
    (N'amr.elsayed@bosla.demo',      N'حل المشكلات'),
    (N'tamer.naguib@bosla.demo',     N'حل المشكلات'),
    (N'tamer.naguib@bosla.demo',     N'إدارة المشاريع'),
    (N'tamer.naguib@bosla.demo',     N'قيادة الفريق'),
    (N'sherif.tawfik@bosla.demo',    N'حل المشكلات'),
    (N'sherif.tawfik@bosla.demo',    N'إدارة المشاريع'),
    (N'sherif.tawfik@bosla.demo',    N'العمل تحت الضغط'),
    (N'reem.galal@bosla.demo',       N'حل المشكلات'),
    (N'reem.galal@bosla.demo',       N'التفكير التحليلي'),
    (N'reem.galal@bosla.demo',       N'إدارة المشاريع'),
    (N'hala.mahmoud@bosla.demo',     N'التفكير التحليلي'),
    (N'hala.mahmoud@bosla.demo',     N'حل المشكلات'),
    (N'hala.mahmoud@bosla.demo',     N'إدارة المشاريع'),
    (N'nihal.rashad@bosla.demo',     N'التواصل الفعال'),
    (N'nihal.rashad@bosla.demo',     N'التفاوض'),
    (N'nihal.rashad@bosla.demo',     N'التفكير التحليلي'),
    (N'rasha.ezzat@bosla.demo',      N'التواصل الفعال'),
    (N'rasha.ezzat@bosla.demo',      N'التفاوض'),
    (N'rasha.ezzat@bosla.demo',      N'حل المشكلات'),
    (N'ziad.amro@bosla.demo',        N'التفاوض'),
    (N'ziad.amro@bosla.demo',        N'التواصل الفعال'),
    (N'ziad.amro@bosla.demo',        N'التفكير التحليلي'),
    (N'mai.abdelhamid@bosla.demo',   N'التحليل المالي'),
    (N'mai.abdelhamid@bosla.demo',   N'التفكير التحليلي'),
    (N'mai.abdelhamid@bosla.demo',   N'إدارة الوقت'),
    (N'islam.ahmed@bosla.demo',      N'التحليل المالي'),
    (N'islam.ahmed@bosla.demo',      N'التفكير التحليلي'),
    (N'islam.ahmed@bosla.demo',      N'إدارة الوقت'),
    (N'marwa.said@bosla.demo',       N'التسويق الرقمي'),
    (N'marwa.said@bosla.demo',       N'الإبداع'),
    (N'marwa.said@bosla.demo',       N'التواصل الفعال'),
    (N'nesrine.khaled@bosla.demo',   N'التسويق الرقمي'),
    (N'nesrine.khaled@bosla.demo',   N'قيادة الفريق'),
    (N'nesrine.khaled@bosla.demo',   N'التخطيط الاستراتيجي'),
    (N'hassan.younis@bosla.demo',    N'التدريب'),
    (N'hassan.younis@bosla.demo',    N'التواصل الفعال'),
    (N'hassan.younis@bosla.demo',    N'إدارة الوقت'),
    (N'aya.yasser@bosla.demo',       N'التدريب'),
    (N'aya.yasser@bosla.demo',       N'التواصل الفعال'),
    (N'aya.yasser@bosla.demo',       N'التفكير التحليلي'),
    (N'hisham.lotfy@bosla.demo',     N'الإبداع'),
    (N'hisham.lotfy@bosla.demo',     N'التصميم'),
    (N'hisham.lotfy@bosla.demo',     N'التواصل الفعال'),
    (N'nadine.emad@bosla.demo',      N'التصميم'),
    (N'nadine.emad@bosla.demo',      N'الإبداع'),
    (N'nadine.emad@bosla.demo',      N'التسويق الرقمي'),
    (N'hany.magdy@bosla.demo',       N'قيادة الفريق'),
    (N'hany.magdy@bosla.demo',       N'التخطيط الاستراتيجي'),
    (N'hany.magdy@bosla.demo',       N'التفاوض'),
    (N'salma.hassan@bosla.demo',     N'قيادة الفريق'),
    (N'salma.hassan@bosla.demo',     N'التخطيط الاستراتيجي'),
    (N'salma.hassan@bosla.demo',     N'التواصل الفعال'),
    (N'youssef.mahmoud@bosla.demo',  N'التدريب'),
    (N'youssef.mahmoud@bosla.demo',  N'التواصل الفعال'),
    (N'youssef.mahmoud@bosla.demo',  N'إدارة الوقت')
) AS D(Email, SkillName)
INNER JOIN Specialists sp ON sp.UserId = (SELECT Id FROM AspNetUsers WHERE Email = D.Email)
INNER JOIN Skills sk ON sk.Name = D.SkillName
WHERE NOT EXISTS (
    SELECT 1 FROM SpecialistSkills ss
    WHERE ss.SpecialistId = sp.Id AND ss.SkillId = sk.Id
);
PRINT N'Seeded SpecialistSkills (150 records).';

PRINT N'Seeding SpecialistTools...';
INSERT INTO SpecialistTools (SpecialistId, ToolId)
SELECT sp.Id, t.Id
FROM (VALUES
    -- Tech: development / devops / data tools
    (N'ahmed.hassan@bosla.demo',     N'GitHub'),
    (N'ahmed.hassan@bosla.demo',     N'Docker'),
    (N'mona.ibrahim@bosla.demo',     N'GitHub'),
    (N'mona.ibrahim@bosla.demo',     N'Jira'),
    (N'nour.ahmed@bosla.demo',       N'GitHub'),
    (N'nour.ahmed@bosla.demo',       N'Jira'),
    (N'sara.mohamed@bosla.demo',     N'Figma'),
    (N'sara.mohamed@bosla.demo',     N'GitHub'),
    (N'ali.abdelrahman@bosla.demo',  N'GitHub'),
    (N'ali.abdelrahman@bosla.demo',  N'Jira'),
    (N'hossam.ibrahim@bosla.demo',   N'GitHub'),
    (N'hossam.ibrahim@bosla.demo',   N'Figma'),
    (N'mohamed.samir@bosla.demo',    N'GitHub'),
    (N'mohamed.samir@bosla.demo',    N'Figma'),
    (N'dina.essam@bosla.demo',       N'GitHub'),
    (N'dina.essam@bosla.demo',       N'Figma'),
    (N'yasmin.adel@bosla.demo',      N'GitHub'),
    (N'yasmin.adel@bosla.demo',      N'Figma'),
    (N'mostafa.kamal@bosla.demo',    N'Docker'),
    (N'mostafa.kamal@bosla.demo',    N'Kubernetes'),
    (N'rania.abdelaziz@bosla.demo',  N'Docker'),
    (N'rania.abdelaziz@bosla.demo',  N'Kubernetes'),
    (N'ayman.sherif@bosla.demo',     N'Docker'),
    (N'ayman.sherif@bosla.demo',     N'Slack'),
    (N'tarek.mahmoud@bosla.demo',    N'AWS'),
    (N'tarek.mahmoud@bosla.demo',    N'Docker'),
    (N'heba.ibrahim@bosla.demo',     N'AWS'),
    (N'heba.ibrahim@bosla.demo',     N'Docker'),
    (N'waleed.hassan@bosla.demo',    N'AWS'),
    (N'waleed.hassan@bosla.demo',    N'Docker'),
    (N'nermeen.adel@bosla.demo',     N'Tableau'),
    (N'nermeen.adel@bosla.demo',     N'Power BI'),
    (N'ashraf.khalil@bosla.demo',    N'Tableau'),
    (N'ashraf.khalil@bosla.demo',    N'Power BI'),
    (N'bassem.sameh@bosla.demo',     N'Docker'),
    (N'bassem.sameh@bosla.demo',     N'GitHub'),
    (N'abdelrahman.nasser@bosla.demo', N'GitHub'),
    (N'abdelrahman.nasser@bosla.demo', N'Docker'),
    (N'fatma.elzahraa@bosla.demo',   N'GitHub'),
    (N'fatma.elzahraa@bosla.demo',   N'Docker'),
    (N'mahmoud.sabry@bosla.demo',    N'GitHub'),
    (N'mahmoud.sabry@bosla.demo',    N'Docker'),
    (N'galal.ahmed@bosla.demo',      N'GitHub'),
    (N'galal.ahmed@bosla.demo',      N'Slack'),
    (N'samah.ibrahim@bosla.demo',    N'GitHub'),
    (N'samah.ibrahim@bosla.demo',    N'Slack'),
    (N'khaled.elrashidy@bosla.demo', N'Jira'),
    (N'khaled.elrashidy@bosla.demo', N'Slack'),
    -- Non-Tech: communication / office tools
    (N'omar.nabil@bosla.demo',       N'Microsoft Teams'),
    (N'omar.nabil@bosla.demo',       N'Zoom'),
    (N'hana.youssef@bosla.demo',     N'Microsoft Teams'),
    (N'hana.youssef@bosla.demo',     N'Zoom'),
    (N'khaled.ali@bosla.demo',       N'Microsoft Teams'),
    (N'khaled.ali@bosla.demo',       N'Zoom'),
    (N'mariam.karim@bosla.demo',     N'Microsoft Teams'),
    (N'mariam.karim@bosla.demo',     N'Zoom'),
    (N'karim.hassan@bosla.demo',     N'Microsoft Teams'),
    (N'karim.hassan@bosla.demo',     N'Zoom'),
    (N'nada.tarek@bosla.demo',       N'Microsoft Teams'),
    (N'nada.tarek@bosla.demo',       N'Zoom'),
    (N'laila.mostafa@bosla.demo',    N'Trello'),
    (N'laila.mostafa@bosla.demo',    N'Microsoft Teams'),
    (N'amr.elsayed@bosla.demo',      N'Trello'),
    (N'amr.elsayed@bosla.demo',      N'Microsoft Teams'),
    (N'tamer.naguib@bosla.demo',     N'Trello'),
    (N'tamer.naguib@bosla.demo',     N'Microsoft Teams'),
    (N'sherif.tawfik@bosla.demo',    N'Trello'),
    (N'sherif.tawfik@bosla.demo',    N'Microsoft Teams'),
    (N'reem.galal@bosla.demo',       N'Trello'),
    (N'reem.galal@bosla.demo',       N'Microsoft Teams'),
    (N'hala.mahmoud@bosla.demo',     N'Trello'),
    (N'hala.mahmoud@bosla.demo',     N'Microsoft Teams'),
    (N'nihal.rashad@bosla.demo',     N'Microsoft Teams'),
    (N'nihal.rashad@bosla.demo',     N'Zoom'),
    (N'rasha.ezzat@bosla.demo',      N'Microsoft Teams'),
    (N'rasha.ezzat@bosla.demo',      N'Zoom'),
    (N'ziad.amro@bosla.demo',        N'Microsoft Teams'),
    (N'ziad.amro@bosla.demo',        N'Zoom'),
    (N'mai.abdelhamid@bosla.demo',   N'Salesforce'),
    (N'mai.abdelhamid@bosla.demo',   N'Power BI'),
    (N'islam.ahmed@bosla.demo',      N'Salesforce'),
    (N'islam.ahmed@bosla.demo',      N'Power BI'),
    (N'marwa.said@bosla.demo',       N'Google Analytics'),
    (N'marwa.said@bosla.demo',       N'Salesforce'),
    (N'nesrine.khaled@bosla.demo',   N'Google Analytics'),
    (N'nesrine.khaled@bosla.demo',   N'Salesforce'),
    (N'hassan.younis@bosla.demo',    N'Microsoft Teams'),
    (N'hassan.younis@bosla.demo',    N'Zoom'),
    (N'aya.yasser@bosla.demo',       N'Microsoft Teams'),
    (N'aya.yasser@bosla.demo',       N'Zoom'),
    (N'hisham.lotfy@bosla.demo',     N'Adobe Photoshop'),
    (N'hisham.lotfy@bosla.demo',     N'Figma'),
    (N'nadine.emad@bosla.demo',      N'Adobe Photoshop'),
    (N'nadine.emad@bosla.demo',      N'Figma'),
    (N'hany.magdy@bosla.demo',       N'Microsoft Teams'),
    (N'hany.magdy@bosla.demo',       N'Slack'),
    (N'salma.hassan@bosla.demo',     N'Microsoft Teams'),
    (N'salma.hassan@bosla.demo',     N'Slack'),
    (N'youssef.mahmoud@bosla.demo',  N'Microsoft Teams'),
    (N'youssef.mahmoud@bosla.demo',  N'Zoom')
) AS D(Email, ToolName)
INNER JOIN Specialists sp ON sp.UserId = (SELECT Id FROM AspNetUsers WHERE Email = D.Email)
INNER JOIN Tools t ON t.Name = D.ToolName
WHERE NOT EXISTS (
    SELECT 1 FROM SpecialistTools st
    WHERE st.SpecialistId = sp.Id AND st.ToolId = t.Id
);
PRINT N'Seeded SpecialistTools (100 records).';

PRINT N'Seeding UserExpertise (primary expertise per specialist user)...';
INSERT INTO UserExpertise (UserId, ExpertiseId)
SELECT u.Id, ex.Id
FROM (VALUES
    (N'ahmed.hassan@bosla.demo',     N'تطوير Backend'),
    (N'mona.ibrahim@bosla.demo',     N'تطوير Backend'),
    (N'nour.ahmed@bosla.demo',       N'تطوير Backend'),
    (N'sara.mohamed@bosla.demo',     N'تطوير Frontend'),
    (N'ali.abdelrahman@bosla.demo',  N'تطوير Frontend'),
    (N'hossam.ibrahim@bosla.demo',   N'تطوير Frontend'),
    (N'mohamed.samir@bosla.demo',    N'تطوير تطبيقات الجوال'),
    (N'dina.essam@bosla.demo',       N'تطوير تطبيقات الجوال'),
    (N'yasmin.adel@bosla.demo',      N'تطوير تطبيقات الجوال'),
    (N'mostafa.kamal@bosla.demo',    N'DevOps'),
    (N'rania.abdelaziz@bosla.demo',  N'DevOps'),
    (N'ayman.sherif@bosla.demo',     N'DevOps'),
    (N'tarek.mahmoud@bosla.demo',    N'الحوسبة السحابية'),
    (N'heba.ibrahim@bosla.demo',     N'الحوسبة السحابية'),
    (N'waleed.hassan@bosla.demo',    N'الحوسبة السحابية'),
    (N'nermeen.adel@bosla.demo',     N'علم البيانات'),
    (N'ashraf.khalil@bosla.demo',    N'علم البيانات'),
    (N'bassem.sameh@bosla.demo',     N'علم البيانات'),
    (N'abdelrahman.nasser@bosla.demo', N'تعلم الآلة'),
    (N'fatma.elzahraa@bosla.demo',   N'تعلم الآلة'),
    (N'mahmoud.sabry@bosla.demo',    N'تعلم الآلة'),
    (N'galal.ahmed@bosla.demo',      N'الأمن السيبراني'),
    (N'samah.ibrahim@bosla.demo',    N'الأمن السيبراني'),
    (N'khaled.elrashidy@bosla.demo', N'الأمن السيبراني'),
    (N'omar.nabil@bosla.demo',       N'طب عام'),
    (N'hana.youssef@bosla.demo',     N'طب عام'),
    (N'khaled.ali@bosla.demo',       N'طب أسنان'),
    (N'mariam.karim@bosla.demo',     N'طب أسنان'),
    (N'karim.hassan@bosla.demo',     N'صيدلة'),
    (N'nada.tarek@bosla.demo',       N'صيدلة'),
    (N'laila.mostafa@bosla.demo',    N'هندسة مدنية'),
    (N'amr.elsayed@bosla.demo',      N'هندسة مدنية'),
    (N'tamer.naguib@bosla.demo',     N'هندسة ميكانيكا'),
    (N'sherif.tawfik@bosla.demo',    N'هندسة ميكانيكا'),
    (N'reem.galal@bosla.demo',       N'هندسة كهرباء'),
    (N'hala.mahmoud@bosla.demo',     N'هندسة كهرباء'),
    (N'nihal.rashad@bosla.demo',     N'قانون'),
    (N'rasha.ezzat@bosla.demo',      N'قانون'),
    (N'ziad.amro@bosla.demo',        N'قانون'),
    (N'mai.abdelhamid@bosla.demo',   N'محاسبة'),
    (N'islam.ahmed@bosla.demo',      N'محاسبة'),
    (N'marwa.said@bosla.demo',       N'تسويق'),
    (N'nesrine.khaled@bosla.demo',   N'تسويق'),
    (N'hassan.younis@bosla.demo',    N'تدريس'),
    (N'aya.yasser@bosla.demo',       N'تدريس'),
    (N'hisham.lotfy@bosla.demo',     N'فنون'),
    (N'nadine.emad@bosla.demo',      N'فنون'),
    (N'hany.magdy@bosla.demo',       N'إدارة أعمال'),
    (N'salma.hassan@bosla.demo',     N'إدارة أعمال'),
    (N'youssef.mahmoud@bosla.demo',  N'تغذية ولياقة')
) AS D(Email, ExpertiseName)
INNER JOIN AspNetUsers u ON u.Email = D.Email
INNER JOIN Expertises ex ON ex.Name = D.ExpertiseName
WHERE NOT EXISTS (
    SELECT 1 FROM UserExpertise ue
    WHERE ue.UserId = u.Id AND ue.ExpertiseId = ex.Id
);
PRINT N'Seeded UserExpertise (50 records).';

PRINT N'All lookup seed data inserted successfully.';
GO
