namespace BoslaPlatform.Infrastructure.Data.Outbox;

/// <summary>
/// Represents a serialised integration event persisted for reliable, asynchronous
/// delivery to a message broker or downstream consumer.
///
/// This entity is part of the <b>Transactional Outbox</b> pattern and implements
/// the <b>Integration Events</b> side of the Hybrid Domain Event Architecture:
///
/// ┌──────────────────────────────────────────────────────────────────────┐
/// │  Hybrid Domain Event Architecture                                   │
/// ├──────────────────────────────────────────────────────────────────────┤
/// │  Local Domain Events  │ Published via MediatR <b>after</b> the      │
/// │                       │ database commit by DomainEventsInterceptor.  │
/// │                       │ Used for synchronous in-process side-effects │
/// │                       │ (send email, invalidate cache, update read   │
/// │                       │ models). Executed in SavedChanges.           │
/// │                       │                                              │
/// │  Integration Events   │ Serialised and persisted <b>before</b> the  │
/// │  (this entity)        │ commit by OutboxSaveChangesInterceptor.      │
/// │                       │ Stored in the OutboxMessages table within    │
/// │                       │ the same database transaction as the domain  │
/// │                       │ data. A future background dispatcher reads   │
/// │                       │ and publishes these to message brokers.      │
/// └──────────────────────────────────────────────────────────────────────┘
///
/// <b>Transaction boundary:</b>
/// OutboxMessage records are INSERTed in the same SaveChanges batch as the
/// domain entities that produced their events. If the transaction rolls back,
/// the outbox records roll back with everything else — guaranteeing that
/// every committed domain change has a corresponding outbox entry.
///
/// <b>Layer isolation:</b>
/// This entity lives exclusively in the Infrastructure layer. The Domain
/// layer has no reference to it and remains completely unaware of the
/// outbox mechanism. The Application layer depends on IAppDbContext,
/// which intentionally does not expose OutboxMessages.
/// </summary>
public class OutboxMessage
{
    /// <summary>
    /// Gets or sets the unique identifier for this outbox message.
    /// Generated by the application; not database-generated.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the full CLR type name of the event
    /// (e.g., "BoslaPlatform.Domain.Events.Apoointments.AppointmentCompletedEvent").
    /// Used by the dispatcher to determine how to deserialise and route the event.
    /// </summary>
    public string EventType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the simple name of the assembly that contains the event type
    /// (e.g., "BoslaPlatform.Domain"). Enables the dispatcher to load the correct
    /// assembly for deserialisation without scanning all loaded assemblies.
    /// </summary>
    public string AssemblyName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the schema version of the event payload.
    /// Reserved for future version-aware migration and dispatching.
    /// Always populated by the interceptor using <see cref="OutboxConstants.EventVersion"/>.
    /// There is no SQL default constraint — the C# initialiser is the single source of truth.
    /// </summary>
    public int EventVersion { get; set; } = OutboxConstants.EventVersion;

    /// <summary>
    /// Gets or sets the serialised JSON payload of the domain event.
    /// This is the data that will be deserialised and forwarded to the message broker.
    /// Serialised using <see cref="OutboxConstants.SerializerOptions"/>.
    /// </summary>
    public string Payload { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets an optional correlation identifier for distributed tracing.
    /// When populated, this value flows from the HTTP request or message header
    /// and is persisted so downstream consumers can correlate events across service
    /// boundaries.
    ///
    /// Not yet populated — reserved for future middleware.
    /// </summary>
    public Guid? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp indicating when this message was created
    /// (when the domain event was captured by OutboxSaveChangesInterceptor).
    /// </summary>
    public DateTime OccurredOnUtc { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp indicating when this message was successfully
    /// processed and published to the message broker.
    /// A null value means the message has not yet been dispatched.
    /// Nullable because dispatch is asynchronous and may not have occurred yet.
    /// </summary>
    public DateTime? ProcessedOnUtc { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp of the most recent processing attempt.
    /// Used by the future dispatcher for retry scheduling and back-off calculations.
    /// A null value means no processing attempt has been made yet.
    /// </summary>
    public DateTime? ProcessingStartedUtc { get; set; }

    /// <summary>
    /// Gets or sets the last error that occurred during processing, if any.
    /// A null value means no error has been recorded, or the last attempt succeeded.
    /// Truncated to <see cref="OutboxConstants.ErrorMaxLength"/> characters
    /// (2000) — full details are always captured in structured application logs.
    /// </summary>
    public string? LastError { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp of the last processing attempt.
    /// Used for retry scheduling and back-off calculations.
    /// A null value means no processing attempt has been made yet.
    /// </summary>
    public DateTime? LastAttemptUtc { get; set; }

    /// <summary>
    /// Gets or sets the number of times processing has been attempted for this message.
    /// Starts at 0 and increments on each attempt.
    /// </summary>
    public int RetryCount { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp before which this message must not be retried.
    /// Used by the dispatcher to implement exponential back-off.
    ///
    /// A null value means either:
    ///   - The message has never been attempted (no failure yet), or
    ///   - The message has reached the maximum retry limit and is permanently failed,
    ///     awaiting a future Dead Letter Queue migration.
    /// </summary>
    public DateTime? NextRetryUtc { get; set; }
}
