<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Behaviours\**" />
    <EmbeddedResource Remove="Behaviours\**" />
    <None Remove="Behaviours\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoslaPlatform.Domain\BoslaPlatform.Domain.csproj" />
    <ProjectReference Include="..\BoslaPlatform.Shared\BoslaPlatform.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Admin\Mappings\" />
    <Folder Include="Features\Authentication\Mappings\" />
    <Folder Include="Features\Authentication\Validators\" />
    <Folder Include="Features\Conversations\Responses\" />
    <Folder Include="Features\Users\Services\" />
    <Folder Include="Features\VideoSessions\Validators\" />
    <Folder Include="Mappings\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Stripe.net" Version="52.0.0" />
  </ItemGroup>


</Project>
