<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Behaviours\**" />
    <Compile Remove="Validators\**" />
    <EmbeddedResource Remove="Behaviours\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Behaviours\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoslaPlatform.Domain\BoslaPlatform.Domain.csproj" />
    <ProjectReference Include="..\BoslaPlatform.Shared\BoslaPlatform.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\Mappings\" />
    <Folder Include="Features\Authentication\Validators\" />
    <Folder Include="EventHandlers\" />
    <Folder Include="Mappings\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
  </ItemGroup>


</Project>
